package com.zi.dal.log.dao;

import com.zi.dal.log.entity.Log;
import com.zi.dal.log.entity.LogExample;
import com.zi.dal.log.entity.LogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int countByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insert(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insertSelective(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<LogWithBLOBs> selectByExampleWithBLOBs(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<Log> selectByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    LogWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleSelective(@Param("record") LogWithBLOBs record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") LogWithBLOBs record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeySelective(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKey(Log record);
}