package com.zi.dal.log.entity;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.op_type
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String opType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.op_type
     *
     * @return the value of log.op_type
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getOpType() {
        return opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.op_type
     *
     * @param opType the value for log.op_type
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setOpType(String opType) {
        this.opType = opType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_id
     *
     * @return the value of log.user_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_id
     *
     * @param userId the value for log.user_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.create_time
     *
     * @return the value of log.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.create_time
     *
     * @param createTime the value for log.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.modify_time
     *
     * @return the value of log.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.modify_time
     *
     * @param modifyTime the value for log.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.is_deleted
     *
     * @return the value of log.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.is_deleted
     *
     * @param isDeleted the value for log.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.sort
     *
     * @return the value of log.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.sort
     *
     * @param sort the value for log.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}