package com.zi.dal.log.entity;

public class LogWithBLOBs extends Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.content
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.content
     *
     * @return the value of log.content
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.content
     *
     * @param content the value for log.content
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.description
     *
     * @return the value of log.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.description
     *
     * @param description the value for log.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}