package com.zi.dal.role.entity;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.parent_tr_id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String parentTrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.modify_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.sort
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.description
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.parent_tr_id
     *
     * @return the value of role.parent_tr_id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getParentTrId() {
        return parentTrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.parent_tr_id
     *
     * @param parentTrId the value for role.parent_tr_id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setParentTrId(String parentTrId) {
        this.parentTrId = parentTrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_time
     *
     * @return the value of role.create_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_time
     *
     * @param createTime the value for role.create_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.is_deleted
     *
     * @return the value of role.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.is_deleted
     *
     * @param isDeleted the value for role.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.modify_time
     *
     * @return the value of role.modify_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.modify_time
     *
     * @param modifyTime the value for role.modify_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.sort
     *
     * @return the value of role.sort
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.sort
     *
     * @param sort the value for role.sort
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.description
     *
     * @return the value of role.description
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.description
     *
     * @param description the value for role.description
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}