package com.zi.dal.right.entity;

import java.util.Date;

public class Right {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.parent_tr_id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String parentTrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.right_name
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String rightName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.create_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.modify_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.sort
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column right.description
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.id
     *
     * @return the value of right.id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.id
     *
     * @param id the value for right.id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.parent_tr_id
     *
     * @return the value of right.parent_tr_id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getParentTrId() {
        return parentTrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.parent_tr_id
     *
     * @param parentTrId the value for right.parent_tr_id
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setParentTrId(String parentTrId) {
        this.parentTrId = parentTrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.right_name
     *
     * @return the value of right.right_name
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getRightName() {
        return rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.right_name
     *
     * @param rightName the value for right.right_name
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setRightName(String rightName) {
        this.rightName = rightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.create_time
     *
     * @return the value of right.create_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.create_time
     *
     * @param createTime the value for right.create_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.is_deleted
     *
     * @return the value of right.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.is_deleted
     *
     * @param isDeleted the value for right.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.modify_time
     *
     * @return the value of right.modify_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.modify_time
     *
     * @param modifyTime the value for right.modify_time
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.sort
     *
     * @return the value of right.sort
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.sort
     *
     * @param sort the value for right.sort
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column right.description
     *
     * @return the value of right.description
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column right.description
     *
     * @param description the value for right.description
     *
     * @mbggenerated Tue Aug 16 17:48:33 ICT 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}