package com.zi.dal.relation.group.right.dao;

import com.zi.dal.relation.group.right.entity.GroupRightRelation;
import com.zi.dal.relation.group.right.entity.GroupRightRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupRightRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int countByExample(GroupRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByExample(GroupRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insert(GroupRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insertSelective(GroupRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<GroupRightRelation> selectByExampleWithBLOBs(GroupRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<GroupRightRelation> selectByExample(GroupRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    GroupRightRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleSelective(@Param("record") GroupRightRelation record, @Param("example") GroupRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") GroupRightRelation record, @Param("example") GroupRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExample(@Param("record") GroupRightRelation record, @Param("example") GroupRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeySelective(GroupRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(GroupRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKey(GroupRightRelation record);
}