package com.zi.dal.sysmenu.entity;

import java.util.Date;

public class SysMenu extends SysMenuCustom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.id
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.title
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.ico
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private String ico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.authority_id
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private String authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.create_time
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.modify_time
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.is_enable
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private String isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.is_deleted
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.sort
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.parent_id
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    private String parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.id
     *
     * @return the value of sys_menu.id
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.id
     *
     * @param id the value for sys_menu.id
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.title
     *
     * @return the value of sys_menu.title
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.title
     *
     * @param title the value for sys_menu.title
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.ico
     *
     * @return the value of sys_menu.ico
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public String getIco() {
        return ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.ico
     *
     * @param ico the value for sys_menu.ico
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setIco(String ico) {
        this.ico = ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.authority_id
     *
     * @return the value of sys_menu.authority_id
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.authority_id
     *
     * @param authorityId the value for sys_menu.authority_id
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.create_time
     *
     * @return the value of sys_menu.create_time
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.create_time
     *
     * @param createTime the value for sys_menu.create_time
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.modify_time
     *
     * @return the value of sys_menu.modify_time
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.modify_time
     *
     * @param modifyTime the value for sys_menu.modify_time
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.is_enable
     *
     * @return the value of sys_menu.is_enable
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.is_enable
     *
     * @param isEnable the value for sys_menu.is_enable
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.is_deleted
     *
     * @return the value of sys_menu.is_deleted
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.is_deleted
     *
     * @param isDeleted the value for sys_menu.is_deleted
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.sort
     *
     * @return the value of sys_menu.sort
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.sort
     *
     * @param sort the value for sys_menu.sort
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.parent_id
     *
     * @return the value of sys_menu.parent_id
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.parent_id
     *
     * @param parentId the value for sys_menu.parent_id
     *
     * @mbggenerated Thu Jan 05 18:29:41 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }
}