package com.zi.dal.relation.group.role.dao;

import com.zi.dal.relation.group.role.entity.GroupRoleRelation;
import com.zi.dal.relation.group.role.entity.GroupRoleRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int countByExample(GroupRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByExample(GroupRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insert(GroupRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insertSelective(GroupRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<GroupRoleRelation> selectByExampleWithBLOBs(GroupRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<GroupRoleRelation> selectByExample(GroupRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    GroupRoleRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleSelective(@Param("record") GroupRoleRelation record, @Param("example") GroupRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") GroupRoleRelation record, @Param("example") GroupRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExample(@Param("record") GroupRoleRelation record, @Param("example") GroupRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeySelective(GroupRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(GroupRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_role_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKey(GroupRoleRelation record);
}