package com.zi.dal.relation.user.role.entity;

import java.util.Date;

public class UserRoleRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.user_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.role_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_relation.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.id
     *
     * @return the value of user_role_relation.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.id
     *
     * @param id the value for user_role_relation.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.user_id
     *
     * @return the value of user_role_relation.user_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.user_id
     *
     * @param userId the value for user_role_relation.user_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.role_id
     *
     * @return the value of user_role_relation.role_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.role_id
     *
     * @param roleId the value for user_role_relation.role_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.create_time
     *
     * @return the value of user_role_relation.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.create_time
     *
     * @param createTime the value for user_role_relation.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.modify_time
     *
     * @return the value of user_role_relation.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.modify_time
     *
     * @param modifyTime the value for user_role_relation.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.is_deleted
     *
     * @return the value of user_role_relation.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.is_deleted
     *
     * @param isDeleted the value for user_role_relation.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.sort
     *
     * @return the value of user_role_relation.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.sort
     *
     * @param sort the value for user_role_relation.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_relation.description
     *
     * @return the value of user_role_relation.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_relation.description
     *
     * @param description the value for user_role_relation.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}