package com.zi.dal.sysroleauthority.dao;

import com.zi.dal.sysroleauthority.entity.SysRoleAuthority;
import com.zi.dal.sysroleauthority.entity.SysRoleAuthorityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysRoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    int countByExample(SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    int deleteByExample(SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    int insert(SysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    int insertSelective(SysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    List<SysRoleAuthority> selectByExample(SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    SysRoleAuthority selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysRoleAuthority record, @Param("example") SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    int updateByExample(@Param("record") SysRoleAuthority record, @Param("example") SysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    int updateByPrimaryKeySelective(SysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_authority
     *
     * @mbggenerated Thu Jan 05 15:18:39 CST 2017
     */
    int updateByPrimaryKey(SysRoleAuthority record);
}