package com.zi.dal.piresource.entity;

import java.util.Date;

public class PiResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi_resource.id
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi_resource.value
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi_resource.permission
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi_resource.create_time
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi_resource.modify_time
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi_resource.is_deleted
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pi_resource.sort
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pi_resource.id
     *
     * @return the value of pi_resource.id
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pi_resource.id
     *
     * @param id the value for pi_resource.id
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pi_resource.value
     *
     * @return the value of pi_resource.value
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pi_resource.value
     *
     * @param value the value for pi_resource.value
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pi_resource.permission
     *
     * @return the value of pi_resource.permission
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pi_resource.permission
     *
     * @param permission the value for pi_resource.permission
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pi_resource.create_time
     *
     * @return the value of pi_resource.create_time
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pi_resource.create_time
     *
     * @param createTime the value for pi_resource.create_time
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pi_resource.modify_time
     *
     * @return the value of pi_resource.modify_time
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pi_resource.modify_time
     *
     * @param modifyTime the value for pi_resource.modify_time
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pi_resource.is_deleted
     *
     * @return the value of pi_resource.is_deleted
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pi_resource.is_deleted
     *
     * @param isDeleted the value for pi_resource.is_deleted
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pi_resource.sort
     *
     * @return the value of pi_resource.sort
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pi_resource.sort
     *
     * @param sort the value for pi_resource.sort
     *
     * @mbggenerated Sun Dec 18 13:40:48 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}