package com.zi.dal.relation.user.right.dao;

import com.zi.dal.relation.user.right.entity.UserRightRelation;
import com.zi.dal.relation.user.right.entity.UserRightRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRightRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int countByExample(UserRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByExample(UserRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insert(UserRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insertSelective(UserRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<UserRightRelation> selectByExampleWithBLOBs(UserRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<UserRightRelation> selectByExample(UserRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    UserRightRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserRightRelation record, @Param("example") UserRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") UserRightRelation record, @Param("example") UserRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExample(@Param("record") UserRightRelation record, @Param("example") UserRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeySelective(UserRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(UserRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKey(UserRightRelation record);
}