package com.zi.dal.sysauthority.entity;

import java.util.Date;

public class SysAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.id
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.name
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.code
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.type
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.is_enable
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private String isEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.parent_id
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.create_time
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.modify_Time
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.is_deleted
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.sort
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_authority.url
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.id
     *
     * @return the value of sys_authority.id
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.id
     *
     * @param id the value for sys_authority.id
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.name
     *
     * @return the value of sys_authority.name
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.name
     *
     * @param name the value for sys_authority.name
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.code
     *
     * @return the value of sys_authority.code
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.code
     *
     * @param code the value for sys_authority.code
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.type
     *
     * @return the value of sys_authority.type
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.type
     *
     * @param type the value for sys_authority.type
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.is_enable
     *
     * @return the value of sys_authority.is_enable
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.is_enable
     *
     * @param isEnable the value for sys_authority.is_enable
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.parent_id
     *
     * @return the value of sys_authority.parent_id
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.parent_id
     *
     * @param parentId the value for sys_authority.parent_id
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.create_time
     *
     * @return the value of sys_authority.create_time
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.create_time
     *
     * @param createTime the value for sys_authority.create_time
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.modify_Time
     *
     * @return the value of sys_authority.modify_Time
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.modify_Time
     *
     * @param modifyTime the value for sys_authority.modify_Time
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.is_deleted
     *
     * @return the value of sys_authority.is_deleted
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.is_deleted
     *
     * @param isDeleted the value for sys_authority.is_deleted
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.sort
     *
     * @return the value of sys_authority.sort
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.sort
     *
     * @param sort the value for sys_authority.sort
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_authority.url
     *
     * @return the value of sys_authority.url
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_authority.url
     *
     * @param url the value for sys_authority.url
     *
     * @mbggenerated Fri Dec 30 14:55:18 CST 2016
     */
    public void setUrl(String url) {
        this.url = url;
    }
}