package com.zi.dal.relation.role.right.entity;

import java.util.Date;

public class RoleRightRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right_relation.id
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right_relation.role_id
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right_relation.right_id
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    private String rightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right_relation.right_type
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    private String rightType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right_relation.create_time
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right_relation.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right_relation.modify_time
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_right_relation.sort
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right_relation.id
     *
     * @return the value of role_right_relation.id
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right_relation.id
     *
     * @param id the value for role_right_relation.id
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right_relation.role_id
     *
     * @return the value of role_right_relation.role_id
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right_relation.role_id
     *
     * @param roleId the value for role_right_relation.role_id
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right_relation.right_id
     *
     * @return the value of role_right_relation.right_id
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public String getRightId() {
        return rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right_relation.right_id
     *
     * @param rightId the value for role_right_relation.right_id
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public void setRightId(String rightId) {
        this.rightId = rightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right_relation.right_type
     *
     * @return the value of role_right_relation.right_type
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public String getRightType() {
        return rightType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right_relation.right_type
     *
     * @param rightType the value for role_right_relation.right_type
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public void setRightType(String rightType) {
        this.rightType = rightType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right_relation.create_time
     *
     * @return the value of role_right_relation.create_time
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right_relation.create_time
     *
     * @param createTime the value for role_right_relation.create_time
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right_relation.is_deleted
     *
     * @return the value of role_right_relation.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right_relation.is_deleted
     *
     * @param isDeleted the value for role_right_relation.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right_relation.modify_time
     *
     * @return the value of role_right_relation.modify_time
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right_relation.modify_time
     *
     * @param modifyTime the value for role_right_relation.modify_time
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_right_relation.sort
     *
     * @return the value of role_right_relation.sort
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_right_relation.sort
     *
     * @param sort the value for role_right_relation.sort
     *
     * @mbggenerated Tue Aug 16 17:42:26 ICT 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}