package com.zi.dal.relation.group.role.entity;

import java.util.Date;

    public class GroupRoleRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_relation.id
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_relation.group_id
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_relation.role_id
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_relation.create_time
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_relation.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_relation.modify_time
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_role_relation.sort
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_relation.id
     *
     * @return the value of group_role_relation.id
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_relation.id
     *
     * @param id the value for group_role_relation.id
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_relation.group_id
     *
     * @return the value of group_role_relation.group_id
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_relation.group_id
     *
     * @param groupId the value for group_role_relation.group_id
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_relation.role_id
     *
     * @return the value of group_role_relation.role_id
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_relation.role_id
     *
     * @param roleId the value for group_role_relation.role_id
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_relation.create_time
     *
     * @return the value of group_role_relation.create_time
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_relation.create_time
     *
     * @param createTime the value for group_role_relation.create_time
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_relation.is_deleted
     *
     * @return the value of group_role_relation.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_relation.is_deleted
     *
     * @param isDeleted the value for group_role_relation.is_deleted
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_relation.modify_time
     *
     * @return the value of group_role_relation.modify_time
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_relation.modify_time
     *
     * @param modifyTime the value for group_role_relation.modify_time
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_role_relation.sort
     *
     * @return the value of group_role_relation.sort
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_role_relation.sort
     *
     * @param sort the value for group_role_relation.sort
     *
     * @mbggenerated Tue Aug 16 17:41:22 ICT 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}