package com.zi.dal.organization.entity;

import java.util.Date;

public class Organization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.parent_to_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String parentToId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.org_name
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.id
     *
     * @return the value of organization.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.id
     *
     * @param id the value for organization.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.parent_to_id
     *
     * @return the value of organization.parent_to_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getParentToId() {
        return parentToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.parent_to_id
     *
     * @param parentToId the value for organization.parent_to_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setParentToId(String parentToId) {
        this.parentToId = parentToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.org_name
     *
     * @return the value of organization.org_name
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.org_name
     *
     * @param orgName the value for organization.org_name
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.create_time
     *
     * @return the value of organization.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.create_time
     *
     * @param createTime the value for organization.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.modify_time
     *
     * @return the value of organization.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.modify_time
     *
     * @param modifyTime the value for organization.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.is_deleted
     *
     * @return the value of organization.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.is_deleted
     *
     * @param isDeleted the value for organization.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.sort
     *
     * @return the value of organization.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.sort
     *
     * @param sort the value for organization.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.description
     *
     * @return the value of organization.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.description
     *
     * @param description the value for organization.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}