package com.zi.dal.sysauthority.dao;

import com.zi.dal.sysauthority.entity.SysAuthority;
import com.zi.dal.sysauthority.entity.SysAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int countByExample(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int deleteByExample(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int insert(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int insertSelective(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    List<SysAuthority> selectByExampleWithBLOBs(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    List<SysAuthority> selectByExample(SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    SysAuthority selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysAuthority record, @Param("example") SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") SysAuthority record, @Param("example") SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int updateByExample(@Param("record") SysAuthority record, @Param("example") SysAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int updateByPrimaryKeySelective(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(SysAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_authority
     *
     * @mbggenerated Thu Jan 05 11:19:42 CST 2017
     */
    int updateByPrimaryKey(SysAuthority record);
}