package com.zi.dal.relation.role.right.dao;

import com.zi.dal.relation.role.right.entity.RoleRightRelation;
import com.zi.dal.relation.role.right.entity.RoleRightRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleRightRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int countByExample(RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByExample(RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insert(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int insertSelective(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<RoleRightRelation> selectByExampleWithBLOBs(RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    List<RoleRightRelation> selectByExample(RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    RoleRightRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleSelective(@Param("record") RoleRightRelation record, @Param("example") RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") RoleRightRelation record, @Param("example") RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByExample(@Param("record") RoleRightRelation record, @Param("example") RoleRightRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeySelective(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(RoleRightRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_right_relation
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    int updateByPrimaryKey(RoleRightRelation record);
}