package com.zi.dal.sysroleuser.entity;

public class SysRoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.id
     *
     * @mbggenerated Thu Jan 05 15:31:39 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.role_id
     *
     * @mbggenerated Thu Jan 05 15:31:39 CST 2017
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_user.user_id
     *
     * @mbggenerated Thu Jan 05 15:31:39 CST 2017
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.id
     *
     * @return the value of sys_role_user.id
     *
     * @mbggenerated Thu Jan 05 15:31:39 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.id
     *
     * @param id the value for sys_role_user.id
     *
     * @mbggenerated Thu Jan 05 15:31:39 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.role_id
     *
     * @return the value of sys_role_user.role_id
     *
     * @mbggenerated Thu Jan 05 15:31:39 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.role_id
     *
     * @param roleId the value for sys_role_user.role_id
     *
     * @mbggenerated Thu Jan 05 15:31:39 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_user.user_id
     *
     * @return the value of sys_role_user.user_id
     *
     * @mbggenerated Thu Jan 05 15:31:39 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_user.user_id
     *
     * @param userId the value for sys_role_user.user_id
     *
     * @mbggenerated Thu Jan 05 15:31:39 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}