package com.zi.dal.group.entity;

import java.util.Date;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.parent_tg_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String parentTgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.group_name
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.id
     *
     * @return the value of group.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.id
     *
     * @param id the value for group.id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.parent_tg_id
     *
     * @return the value of group.parent_tg_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getParentTgId() {
        return parentTgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.parent_tg_id
     *
     * @param parentTgId the value for group.parent_tg_id
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setParentTgId(String parentTgId) {
        this.parentTgId = parentTgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.group_name
     *
     * @return the value of group.group_name
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.group_name
     *
     * @param groupName the value for group.group_name
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.create_time
     *
     * @return the value of group.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.create_time
     *
     * @param createTime the value for group.create_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.modify_time
     *
     * @return the value of group.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.modify_time
     *
     * @param modifyTime the value for group.modify_time
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.is_deleted
     *
     * @return the value of group.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.is_deleted
     *
     * @param isDeleted the value for group.is_deleted
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.sort
     *
     * @return the value of group.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.sort
     *
     * @param sort the value for group.sort
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.description
     *
     * @return the value of group.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.description
     *
     * @param description the value for group.description
     *
     * @mbggenerated Sun Aug 28 19:26:27 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }
}